# Quarkus Project Configuration
quarkus.application.name=testgenesis-cms

# HTTP Configuration
quarkus.http.port=8080

# gRPC Configuration
quarkus.grpc.server.use-separate-server=true
quarkus.grpc.server.port=9000
quarkus.grpc.server.netty.permit-keep-alive-without-calls=true
quarkus.grpc.server.netty.permit-keep-alive-time=10s

# Logging
quarkus.log.level=INFO
quarkus.log.category."me.hsgamer.testgenesis".level=DEBUG

# OpenAPI / Swagger
quarkus.smallrye-openapi.path=/openapi
# Hibernate / H2
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./testgenesis-db;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true
